### ISSUE TITLE
NWBRecording::openFile assumes ElectricalSeries

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/aqnwb#51]
`NWBRecording::openFile` currently requires:

https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/nwb/NWBRecording.cpp#L22

to be provided, which are used to create `ElectricalSeries` object for ephys recordings:

https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/nwb/NWBRecording.cpp#L33-L34

With the pattern where we have separate `createElectricalSeries` (and respective other functions for other types), the `openFile` method should not assume what types of recordings a user wants to make, but the user should call the `createElectricalSeries` functions separately to create any recordings they want. 

**Proposed solution**

Remove the `std::vector<Types::ChannelVector> recordingArrays` argument from `NWBRecording::openFile` and update tests to call the `createElectricalSeries` function separately.

**Comment by stephprince** [comment]
Closing because we have changed the workflow and no longer use the openFile structure
