### ISSUE TITLE
Shadowing of variables

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/aqnwb#60]
Variables are being shadowed because function arguments can class members use the same naming convention. E.g.,

https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/Channel.hpp#L56-L59

defines the member variable `name` and the constructor also defined `name` as constructor argument:

https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/Channel.hpp#L21

this results in 

https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/Channel.cpp#L16-L24

where the object member `name` is being initialize with the constructor argument `name`. This results in a lot of compiler warnings and can also be confusing to read. 

Related to #9

**Comment by oruebel** [comment]
@stephprince any thoughts on this? The shadowing of variables is causing some issues with the read. Do you have a preference on the naming convention we should use to avoid naming conflicts between parameters of functions and the member variables of the class/object?

**Comment by stephprince** [comment]
I am good with using `m_` to indicate member variables to avoid naming conflicts. 

I was using `this->` to indicate member variables in some places, but I don't think that fully fixed the warnings when a function argument had the same name as the member variable. So I am good to update to using `m_` consistently.

**Comment by oruebel** [comment]
> I was using `this->` to indicate member variables in some places, but I don't think that fully fixed the warnings

Yeah, using `this->` really  only addresses the issue inside of regular functions, but the problem still remains, in particular on the constructor level. One place, where this got me in trouble was when I was syncing the read PR with main branch. The "fun" thing that had happened was the following:

- `Container` defines a member `io`
- The constructors of `NWBFile` and `Container` have a parameter `io` (shadowing the `Container.io` member)
- The automatic diff from git merge, falsely created a member `NWBFile.io`. So NWBFile had two members `io`, one from `Container::io` and one from `NWBFile::io`, which in turn let to a Segfault because the constructor set the `Container::io` member that it inherited but not the  `NWBFile::io` member. As a result `this->io` was a `nullptr`, so even just calling `io->getFileName()` resulted in a Segfault. 

Admittedly, that was just a mistake of the automatic diff and removing the duplicate `NWBFile.io` member fixed the problem. But shadowing of members made it harder to detect this strange error.

**Comment by oruebel** [comment]
> I am good with using `m_` to indicate member variables to avoid naming conflicts.

Sounds good.
